// Generated by https://quicktype.io

export interface PokemonListResponse {
  count:     number;
  next?:     string;
  previous?: string;
  results:   SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  id:   number;
  img:  string;
  icon: string;
  url?: string;
}
